version: '3.8'

services:
  backend:
    image: ${DOCKER_USER}/backend:latest
    container_name: tareas-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=tareasdb
    depends_on:
      - mysql

  frontend:
    image: ${DOCKER_USER}/frontend:latest
    container_name: tareas-frontend
    restart: always
    ports:
      - "3000:80"

  mysql:
    image: mysql:8.0
    container_name: tareas-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=tareasdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
