version: "3.9"

services:
  db:
    image: mysql:8
    container_name: tareas-mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tareas_db
    ports:
      - "3307:3306"
    volumes:
      - tareas_mysql_data_dev:/var/lib/mysql
    networks:
      - tareas_net

  backend:
    build:
      context: ../app/backend
      dockerfile: ../../docker/Dockerfile.backend
    container_name: tareas-backend-dev
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: tareas_db
      DB_PORT: 3306
    volumes:
      - ../app/backend:/usr/src/app
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - tareas_net

  frontend:
    build:
      context: ../app/frontend
      dockerfile: ../../docker/Dockerfile.frontend
    container_name: tareas-frontend-dev
    volumes:
      - ../app/frontend:/usr/src/app
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - tareas_net

networks:
  tareas_net:

volumes:
  tareas_mysql_data_dev:
